"""initial data

Revision ID: 173d9c67d0c5
Revises: c430472c4b3a
Create Date: 2023-01-17 22:17:05.886664-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173d9c67d0c5'
down_revision = 'c430472c4b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
