"""initial data

Revision ID: 1d8c2e4e8c3e
Revises: 173d9c67d0c5
Create Date: 2023-01-17 22:31:14.695085-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8c2e4e8c3e'
down_revision = '173d9c67d0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('tenant', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('tenant', 'end_data')
    op.drop_column('tenant', 'start_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('start_data', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('end_data', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('tenant', 'start_date')
    op.drop_column('tenant', 'end_date')
    # ### end Alembic commands ###
