"""initial data

Revision ID: 2309a56d9856
Revises: 3da02aee2aaa
Create Date: 2023-01-17 21:51:08.699650-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2309a56d9856'
down_revision = '3da02aee2aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('end_data', sa.Date(), nullable=True))
    op.add_column('tenant', sa.Column('start_data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'start_data')
    op.drop_column('tenant', 'end_data')
    # ### end Alembic commands ###
