"""initial data

Revision ID: 2539ef6ca748
Revises: 7ff934f00bed
Create Date: 2023-01-03 14:57:38.983016-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2539ef6ca748'
down_revision = '7ff934f00bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
