"""initial data

Revision ID: 36e70404df84
Revises: 978dc66a93f4
Create Date: 2023-01-12 01:03:13.792828-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e70404df84'
down_revision = '978dc66a93f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
