"""initial data

Revision ID: 3da02aee2aaa
Revises: a8b2e2c86c83
Create Date: 2023-01-17 08:43:46.846098-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da02aee2aaa'
down_revision = 'a8b2e2c86c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    op.add_column('branch', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branch', 'tenant', ['tenant_id'], ['id'])
    op.add_column('company', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'tenant', ['tenant_id'], ['id'])
    op.add_column('course', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'tenant', ['tenant_id'], ['id'])
    op.add_column('program', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'program', 'tenant', ['tenant_id'], ['id'])
    op.add_column('quiz', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quiz', 'tenant', ['tenant_id'], ['id'])
    op.add_column('user', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tenant_id')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'tenant_id')
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.drop_column('program', 'tenant_id')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'tenant_id')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'tenant_id')
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'tenant_id')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
