"""initial data

Revision ID: 4842c7eb55b1
Revises: e95174d6faf7
Create Date: 2023-01-17 22:48:38.884499-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4842c7eb55b1'
down_revision = 'e95174d6faf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('discription', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('license_no', sa.Integer(), nullable=True))
    op.drop_column('tenant', 'end_date')
    op.drop_column('tenant', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tenant', 'license_no')
    op.drop_column('tenant', 'discription')
    # ### end Alembic commands ###
