"""initial data

Revision ID: 5e40d2e932d4
Revises: 1d8c2e4e8c3e
Create Date: 2023-01-17 22:45:43.396812-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e40d2e932d4'
down_revision = '1d8c2e4e8c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('discription', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('license_no', sa.Integer(), nullable=True))
    op.drop_column('tenant', 'end_date')
    op.drop_column('tenant', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tenant', 'license_no')
    op.drop_column('tenant', 'discription')
    # ### end Alembic commands ###
