"""initial data

Revision ID: 5e7d35e51693
Revises: 4842c7eb55b1
Create Date: 2023-01-17 22:59:48.648023-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7d35e51693'
down_revision = '4842c7eb55b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('tenant', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('tenant', 'license_no')
    op.drop_column('tenant', 'discription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('license_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tenant', 'start_date')
    op.drop_column('tenant', 'end_date')
    # ### end Alembic commands ###
