"""initial data

Revision ID: 7ff934f00bed
Revises: f85525c27973
Create Date: 2023-01-03 14:56:34.020198-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff934f00bed'
down_revision = 'f85525c27973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
