"""initial data

Revision ID: 978dc66a93f4
Revises: dc1ac9e3c964
Create Date: 2023-01-11 21:52:58.383991-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978dc66a93f4'
down_revision = 'dc1ac9e3c964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
