"""initial data

Revision ID: a8b2e2c86c83
Revises: 36e70404df84
Create Date: 2023-01-12 01:06:39.205689-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b2e2c86c83'
down_revision = '36e70404df84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
