"""initial data

Revision ID: b8378f6dee4f
Revises: fa2e91e47e2f
Create Date: 2023-01-05 01:36:44.396577-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8378f6dee4f'
down_revision = 'fa2e91e47e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
