"""initial data

Revision ID: c430472c4b3a
Revises: 2309a56d9856
Create Date: 2023-01-17 22:08:39.903483-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c430472c4b3a'
down_revision = '2309a56d9856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('branch', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('company', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('program', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('program', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('quiz', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('quiz', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('tenant', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('tenant', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('tenant', 'updated_at')
    op.drop_column('tenant', 'created_at')
    op.drop_column('quiz', 'updated_at')
    op.drop_column('quiz', 'created_at')
    op.drop_column('program', 'updated_at')
    op.drop_column('program', 'created_at')
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    op.drop_column('branch', 'updated_at')
    op.drop_column('branch', 'created_at')
    # ### end Alembic commands ###
