"""initial data

Revision ID: cd9e37af9a7b
Revises: c6532cebcbfc
Create Date: 2023-01-18 22:03:56.028161-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9e37af9a7b'
down_revision = 'c6532cebcbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
