"""initial data

Revision ID: d9817f55c0ec
Revises: 2539ef6ca748
Create Date: 2023-01-03 15:16:24.139344-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9817f55c0ec'
down_revision = '2539ef6ca748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
