"""initial data

Revision ID: dc1ac9e3c964
Revises: b8378f6dee4f
Create Date: 2023-01-05 02:52:35.515276-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1ac9e3c964'
down_revision = 'b8378f6dee4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_branch_contact'), 'branch', ['contact'], unique=True)
    op.create_index(op.f('ix_branch_title'), 'branch', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_title'), table_name='branch')
    op.drop_index(op.f('ix_branch_contact'), table_name='branch')
    # ### end Alembic commands ###
