"""initial data

Revision ID: e95174d6faf7
Revises: 5e40d2e932d4
Create Date: 2023-01-17 22:48:01.927744-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95174d6faf7'
down_revision = '5e40d2e932d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('tenant', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('tenant', 'license_no')
    op.drop_column('tenant', 'discription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('license_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tenant', 'start_date')
    op.drop_column('tenant', 'end_date')
    # ### end Alembic commands ###
