"""initial data

Revision ID: f2f8e560d64b
Revises: cd9e37af9a7b
Create Date: 2023-01-18 22:12:37.016594-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f8e560d64b'
down_revision = 'cd9e37af9a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('tenant', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'start_date')
    op.drop_column('tenant', 'end_date')
    # ### end Alembic commands ###
