"""initial data

Revision ID: f85525c27973
Revises: c8ad54a8f41a
Create Date: 2023-01-03 14:51:38.004983-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85525c27973'
down_revision = 'c8ad54a8f41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
