"""initial data

Revision ID: fa2e91e47e2f
Revises: d8df47d459db
Create Date: 2023-01-05 01:24:27.761355-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2e91e47e2f'
down_revision = 'd8df47d459db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_branch', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.drop_constraint('company_branch_brnach_id_fkey', 'company_branch', type_='foreignkey')
    op.create_foreign_key(None, 'company_branch', 'branch', ['branch_id'], ['id'])
    op.drop_column('company_branch', 'brnach_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_branch', sa.Column('brnach_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company_branch', type_='foreignkey')
    op.create_foreign_key('company_branch_brnach_id_fkey', 'company_branch', 'branch', ['brnach_id'], ['id'])
    op.drop_column('company_branch', 'branch_id')
    # ### end Alembic commands ###
